Task 1: Create a 2D numpy array.


In [1]:
import numpy as np


In [2]:
def CreateSudoku():
    arr = np.array([[3,3, 0, 1],
                    [0, 1, 3, 2],
                    [0, 0, 2, 3],
                    [0, 0, 0, 4]])
    return arr
    # arr.shape


In [3]:
sudoku = CreateSudoku()
print(sudoku)


[[3 3 0 1]
 [0 1 3 2]
 [0 0 2 3]
 [0 0 0 4]]


Task 2: Create a class 'Sudoku', create idBoardValid(board).


In [4]:
class Sudoku:
    def __init__(self, sudoku) -> None:
        self.sudoku = sudoku

    def isBoardValid(self):
        # print(self.sudoku)
        st = set()
        cnt = 0
        for i in self.sudoku:
            for j in i:
                if j == 0:
                    continue
                else:
                    st.add(j)
                    cnt += 1
            if len(st) != cnt:
                return 0
            else:
                st.clear()
                cnt = 0

        for i in range(self.sudoku.shape[1]):
            x = self.sudoku[:, i]

            st1 = set()
            cnt1 = 0
            for it in x:
                if it == 0:
                    continue
                else:
                    st1.add(it)
                    cnt1 += 1
            if len(st1) != cnt1:
                return 0
            else:
                st1.clear()
                cnt1 = 0

        stat1 = set()
        c1 = 0
        stat2 = set()
        c2 = 0
        stat3 = set()
        c3 = 0
        stat4 = set()
        c4 = 0

        for i in range(0, 2):
            for j in range(0, 2):
                if self.sudoku[i, j] == 0:
                    continue
                else:
                    stat1.add(self.sudoku[i, j])
                    c1 += 1
        if len(stat1) != c1:
            return 0

        
        for i in range(2, 4):
            for j in range(2, 4):
                if self.sudoku[i, j] == 0:
                    continue
                else:
                    stat2.add(self.sudoku[i, j])
                    c2 += 1
        if len(stat2) != c2:
            return 0


        for i in range(2, 2):
            for j in range(0, 2):
                if self.sudoku[i, j] == 0:
                    continue
                else:
                    stat3.add(self.sudoku[i, j])
                    c3 += 1
        if len(stat3) != c3:
            return 0

        for i in range(0, 2):
            for j in range(2, 4):
                if self.sudoku[i, j] == 0:
                    continue
                else:
                    stat4.add(self.sudoku[i, j])
                    c4 += 1
        if len(stat4) != c4:
            return 0

        
        return 1


In [5]:
t1 = Sudoku(sudoku)
ck = t1.isBoardValid()

if ck == 0:
    print("Not a valid board!")
else:
    print("A valid board!")


Not a valid board!
