Task 1: Create a 2D numpy array


In [11]:
import numpy as np


In [12]:
def CreateSudoku():
    arr = np.array([[3, 0, 0, 1], [0, 1, 3, 2], [0, 0, 2, 3], [0, 0, 0, 4]])
    return arr
    # arr.shape


In [13]:
sudoku = CreateSudoku()
print(sudoku)


[[3 0 3 1]
 [0 1 3 2]
 [0 0 2 3]
 [0 0 0 4]]


Task 2: Create a class 'Sudoku', create idBoardValid(board).


In [14]:
from ctypes import sizeof


class Sudoku:
    def __init__(self, sudoku) -> None:
        self.sudoku = sudoku

    def isBoardValid(self):
        for i in range(4):
            row = {}
            col = {}
            bl = {}

            row_c = 2 * (i//2)
            col_c = 2 * (i % 2)

            for j in range(4):
                if self.sudoku[i][j] != 0 and self.sudoku[i][j] in row:
                    return False

            row[self.sudoku[i][j]] = 1

            if self.sudoku[j][i] != 0 and self.sudoku[j][i] in col:
                return False

            col[self.sudoku[j][i]] = 1

            rc = row_c + j//2
            cc = col_c + j % 2

            if self.sudoku[rc][cc] in bl and self.sudoku[rc][cc] != 0:
                return False

            bl[self.sudoku[rc][cc]] = 1

        return True


In [15]:
t1 = Sudoku(sudoku)
ck = t1.isBoardValid()

if ck == False:
    print("Not a valid board!")
else:
    print("A valid board!")


A valid board!
