# This is test.


In [10]:
import numpy as np


In [11]:
arr = np.array([[3, 0, 0, 1], [0, 1, 3, 2], [0, 0, 2, 3], [0, 0, 0, 4]])


In [13]:
for i in range(arr.shape[1]):
    print(arr[:, i])


[3 0 0 0]
[0 1 0 0]
[0 3 2 0]
[1 2 3 4]


In [15]:
import numpy as np


In [20]:

a = np.array([[1, 2, 3, 4], [4, 5, 6, 6], [7, 8, 9, 7], [10, 11, 12, 88]])

for x in range(0, 2):
    for y in range(0, 2):
        print(a[x, y], end=" ")
    print()


1 2 
4 5 
