In [15]:
import numpy as np


In [16]:
arr = np.array(((1, 2, 3, 4, 5), (6, 7, 8, 9, 10)))

print(arr)
print(type(arr))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [25]:
a = np.array([[1, 2, 3, 4], [4, 5, 6, 2], [6, 7, 8, 9]])
print(a)
print(type(a))
print(a.shape)


[[1 2 3 4]
 [4 5 6 2]
 [6 7 8 9]]
<class 'numpy.ndarray'>
(3, 4)


Check dimension(s)


In [26]:
print(arr.ndim)
print(a.ndim)
print(arr.shape)
print(a.shape)

2
2
(2, 5)
(3, 4)


Create an array with 5 dimensions and verify that it has 5 dimensions:

In [27]:
b = np.array([1, 2, 3, 4, 5], ndmin=5)
print(b)
print("The number of dimensions:", b.ndim)
print(b.dtype)


[[[[[1 2 3 4 5]]]]]
The number of dimensions: 5
int32
