In [1]:
from numpy import random

In [2]:
x = random.rand()

In [3]:
print(x)

0.683142283093923


In [6]:
from random import randint


x = random.randint(100)

In [7]:
print(x)

94


In [10]:
x = random.randint(100, size=(5))

In [13]:
print(x)

[75 22 77  6 67]


In [14]:
y = random.randint(100, size=(3, 5))

In [15]:
print(y)

[[34 48 31 80 93]
 [49 41 55 44 47]
 [19 32 88 16 79]]


In [18]:
lst = [10,15,20,25,30,45]
z = random.choice(lst, size=(3,3))
print(z)

[[45 20 15]
 [30 25 15]
 [15 20 20]]
