1. take n, create n\*n matrix, populate them with random number between 0 to 1.


In [56]:
import numpy as np
import math


In [57]:
from numpy import random
n = int(input("Take n: "))

rnum = random.rand(n, n)

print(rnum)


[[0.77587789 0.58175791 0.70949558 0.74856419]
 [0.15069597 0.29545337 0.24101034 0.48517787]
 [0.55120977 0.78469715 0.31901371 0.00360919]
 [0.87177745 0.53205386 0.34004765 0.0285416 ]]


2. Find L2 norm


In [58]:
# from cmath import sqrt
from numpy import linalg
arr = rnum.reshape(-1,)

l2N = linalg.norm(arr)
print("L2 norm using function:", l2N)

x = 0
for i in arr:
    x += i*i
sx = (math.sqrt(x))
print("L2 norm using iteration:", sx)


L2 norm using function: 2.1420867107895942
L2 norm using iteration: 2.142086710789594


3.  Find the trace


In [59]:
m, n = 0, 0

for i in arr:
    m += i*i
    n += m
print("Trace of the matrix:", n)


Trace of the matrix: 44.44538676636133
